export const keyboardLayout = [
  [
    { code: "Escape", value: "", className: "bg-body-secondary" },
    { code: "Digit1", value: "1" },
    { code: "Digit2", value: "2" },
    { code: "Digit3", value: "3" },
    { code: "Digit4", value: "4" },
    { code: "Digit5", value: "5" },
    { code: "Digit6", value: "6" },
    { code: "Digit7", value: "7" },
    { code: "Digit8", value: "8" },
    { code: "Digit9", value: "9" },
    { code: "Digit0", value: "0" },
    { code: "Minus", value: "-" },
    { code: "Equal", value: "=" },
    { code: "Backspace", value: "", className: "bg-body-secondary" },
  ],
  [
    { code: "Tab", value: "", className: "bg-body-secondary" },
    { code: "KeyQ", value: "Q" },
    { code: "KeyW", value: "W" },
    { code: "KeyE", value: "E" },
    { code: "KeyR", value: "R" },
    { code: "KeyT", value: "T" },
    { code: "KeyY", value: "Y" },
    { code: "KeyU", value: "U" },
    { code: "KeyI", value: "I" },
    { code: "KeyO", value: "O" },
    { code: "KeyP", value: "P" },
    { code: "BracketLeft", value: "[" },
    { code: "BracketRight", value: "]" },
    { code: "Backslash", value: "\\" },
  ],
  [
    { code: "CapsLock", value: "", className: "bg-body-secondary" },
    { code: "KeyA", value: "A" },
    { code: "KeyS", value: "S" },
    { code: "KeyD", value: "D" },
    { code: "KeyF", value: "F" },
    { code: "KeyG", value: "G" },
    { code: "KeyH", value: "H" },
    { code: "KeyJ", value: "J" },
    { code: "KeyK", value: "K" },
    { code: "KeyL", value: "L" },
    { code: "Semicolon", value: ";" },
    { code: "Quote", value: "'" },
    { code: "Enter", value: "", className: "bg-body-secondary" },
  ],
  [
    { code: "ShiftLeft", value: "", className: "bg-body-secondary" },
    { code: "KeyZ", value: "Z" },
    { code: "KeyX", value: "X" },
    { code: "KeyC", value: "C" },
    { code: "KeyV", value: "V" },
    { code: "KeyB", value: "B" },
    { code: "KeyN", value: "N" },
    { code: "KeyM", value: "M" },
    { code: "Comma", value: "," },
    { code: "Period", value: "." },
    { code: "Slash", value: "/" },
    { code: "ShiftRight", value: "", className: "bg-body-secondary" },
  ],
  [{ code: "Space", value: "", className: "spacebar" }],
];
